# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Client - Build, Install, Test

on:
  push:
    paths-ignore:
      - '.github/workflows/yarals.yml'
      - 'server/tests/*'
  pull_request:
    branches: [ language-server ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 8.x ]
        python-version: [ 3.8 ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pylint pytest pytest-asyncio wheel
        pip wheel ./server/
        pip install $(ls *.whl)
        npm ci
        npm run postinstall
    - name: Compile Source
      run: npm run compile
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: npm test
